name: Test CI/CD Pipeline

on:
  push:
    branches:
      - main
      - jqdeploy
  pull_request:
    branches:
      - main

env:
  AUTH_SERVICE_IMAGE: "musiclibrary/auth_service"
  SONG_SERVICE_IMAGE: "musiclibrary/song_service"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 20.x

      # - name: Install frontend dependencies
      #   run: |
      #     cd frontend
      #     npm install

      # - name: Install backend dependencies
      #   run: |
      #     cd backend
      #     npm install

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      #Images
      - name: Login to Amazon ECR
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com"

      - name: Create ECR repository for Auth Service
        run: |
          aws ecr describe-repositories --repository-names $AUTH_SERVICE_IMAGE || \
          aws ecr create-repository --repository-name $AUTH_SERVICE_IMAGE

      - name: Create ECR repository for Song Service
        run: |
          aws ecr describe-repositories --repository-names $SONG_SERVICE_IMAGE || \
          aws ecr create-repository --repository-name $SONG_SERVICE_IMAGE

      - name: Build, tag, and push Docker Auth image
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          AUTH_REPO_URI="$AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$AUTH_SERVICE_IMAGE"
          docker build -t music_library -f ./aws.dockerfile ./backend/auth_service
          docker tag music_library:latest $AUTH_REPO_URI:latest
          docker push $AUTH_REPO_URI:latest

      - name: Build, tag, and push Docker Song image
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          SONG_REPO_URI="$AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$SONG_SERVICE_IMAGE"
          docker build -t music_library -f ./aws.dockerfile ./backend/song_service
          docker tag music_library:latest $SONG_REPO_URI:latest
          docker push $SONG_REPO_URI:latest

      # - name: Login to Docker Hub
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # - name: Build and push Frontend Image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./frontend
      #     push: true
      #     tags: ptamayo25/uucnh-music-library:frontend

      # - name: Build and push Auth Service Image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./backend/auth-service
      #     push: true
      #     tags: ptamayo25/uucnh-music-library:auth-service

      # - name: Build and push Song Service Image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./backend/song-service
      #     push: true
      #     tags: ptamayo25/uucnh-music-library:song-service

      # - name: Run frontend tests
      #   run: |
      #     cd frontend
      #     npm run test

      # - name: Run backend tests
      #   run: |
      #     cd backend
      #     npm run test
      # - name: Build

# deploy:
#   needs: build
#   runs-on: ubuntu-latest

#   steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Deploy to Production
#       run: echo "Deploying to production (not really)"
